In [1]:
import tensorflow as tf

2023-02-20 14:45:56.730445: I tensorflow/core/platform/cpu_feature_guard.cc:193] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
2023-02-20 14:45:58.423304: W tensorflow/compiler/xla/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libnvinfer.so.7'; dlerror: libnvinfer.so.7: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: :/home/soumik/anaconda3/pkgs/cudatoolkit-11.2.2-hbe64b41_10/lib/
2023-02-20 14:45:58.423498: W tensorflow/compiler/xla/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libnvinfer_plugin.so.7'; dlerror: libnvinfer_plugin.so.7: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: :/home/soumik/anaconda3/pkgs/cudatoolkit-11.2.2-hbe64b41_10/lib/


In [2]:
print(tf.__version__)

2.11.0


In [5]:
number=tf.constant(7)
number

<tf.Tensor: shape=(), dtype=int32, numpy=7>

In [8]:
number1=tf.constant(7)
number2=tf.constant(7)
number1*number2

<tf.Tensor: shape=(), dtype=int32, numpy=49>

In [6]:
number.ndim

0

In [4]:
changable_tensor=tf.Variable([10,7])
changable_tensor

<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([10,  7], dtype=int32)>

In [5]:
changable_tensor[1].assign(5)
changable_tensor

<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([10,  5], dtype=int32)>

In [13]:
random_numbers=tf.random.Generator.from_seed(7)
random_numbers=random_numbers.normal(shape=(3,2))
random_numbers

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[-1.3240396 ,  0.2878567 ],
       [-0.8757901 , -0.08857017],
       [ 0.69211644,  0.84215707]], dtype=float32)>

In [44]:
# tf.random.set_seed(7)  #does not canges results
shuffled=tf.random.shuffle(random_numbers)
shuffled

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[ 0.69211644,  0.84215707],
       [-0.8757901 , -0.08857017],
       [-1.3240396 ,  0.2878567 ]], dtype=float32)>

In [2]:
import numpy as np
numpy_A=np.arange(1,25,dtype=np.int32)
numpy_A

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24], dtype=int32)

In [5]:
tensor_A=tf.constant(numpy_A)
tensor_B=tf.constant(numpy_A,shape=(2,3,4))
tensor_A, tensor_B

(<tf.Tensor: shape=(24,), dtype=int32, numpy=
 array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
        18, 19, 20, 21, 22, 23, 24], dtype=int32)>,
 <tf.Tensor: shape=(2, 3, 4), dtype=int32, numpy=
 array([[[ 1,  2,  3,  4],
         [ 5,  6,  7,  8],
         [ 9, 10, 11, 12]],
 
        [[13, 14, 15, 16],
         [17, 18, 19, 20],
         [21, 22, 23, 24]]], dtype=int32)>)

In [8]:
tensor_B.ndim, tensor_B.shape, tf.size(tensor_B), tf.size(tensor_B).numpy()

(3, TensorShape([2, 3, 4]), <tf.Tensor: shape=(), dtype=int32, numpy=24>, 24)

In [22]:
#Expanding dimesions of tensors
tensor_C=tensor_B[:,:,:,tf.newaxis]
tensor_C=tensor_B[...,tf.newaxis] 
tensor_C=tf.expand_dims(tensor_B,axis=2) #preferred method to expand tensor
tensor_C

<tf.Tensor: shape=(2, 3, 1, 4), dtype=int32, numpy=
array([[[[ 1,  2,  3,  4]],

        [[ 5,  6,  7,  8]],

        [[ 9, 10, 11, 12]]],


       [[[13, 14, 15, 16]],

        [[17, 18, 19, 20]],

        [[21, 22, 23, 24]]]], dtype=int32)>

In [25]:
#Tensor Operations
tensor_D=tf.constant(np.arange(1,10),shape=(3,3),dtype=np.int32)
tensor_D

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]], dtype=int32)>

In [31]:
tensor_D+10
tensor_D-20
tensor_D@tensor_D #Matrix Multiplication

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[ 30,  36,  42],
       [ 66,  81,  96],
       [102, 126, 150]], dtype=int32)>

In [36]:
tf.multiply(tensor_D,10)

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[10, 20, 30],
       [40, 50, 60],
       [70, 80, 90]], dtype=int32)>

In [53]:
tensor_G=tf.constant(np.arange(1,5),shape=(2,2),dtype=np.float64)
tf.linalg.inv(tensor_G)

<tf.Tensor: shape=(2, 2), dtype=float64, numpy=
array([[-2. ,  1. ],
       [ 1.5, -0.5]])>

In [58]:
#Changing datatype
x=tf.constant(7)
x.dtype #-->int32
x=tf.cast(x,tf.float16)
x.dtype #-->float16

tf.float16

In [72]:
X=tf.constant(np.random.random(50),dtype=tf.float32)
X

<tf.Tensor: shape=(50,), dtype=float32, numpy=
array([0.6769183 , 0.07490148, 0.6549518 , 0.87648684, 0.7580716 ,
       0.45800442, 0.9446268 , 0.03818179, 0.8553772 , 0.35888138,
       0.45612714, 0.0316969 , 0.9112594 , 0.039164  , 0.34995157,
       0.36895567, 0.3138207 , 0.09978618, 0.981965  , 0.43730152,
       0.7018339 , 0.8094853 , 0.35555363, 0.01055731, 0.3302894 ,
       0.05050443, 0.38006905, 0.3618443 , 0.44005412, 0.4561432 ,
       0.81556684, 0.72564656, 0.4918337 , 0.36423993, 0.38378862,
       0.6738538 , 0.55652696, 0.26036695, 0.6176906 , 0.6886839 ,
       0.6344165 , 0.70579374, 0.7297625 , 0.20342365, 0.68280315,
       0.3661384 , 0.6702554 , 0.01086433, 0.59286696, 0.09979749],
      dtype=float32)>

In [73]:
var=tf.math.reduce_variance(X)
std=tf.math.reduce_std(X)
var.numpy(),std.numpy()

(0.07459514, 0.2731211)

In [75]:
max_ind=tf.argmax(X)
X[max_ind]==tf.reduce_max(X)

<tf.Tensor: shape=(), dtype=bool, numpy=True>

In [79]:
#Removing single dimensions
tf.random.set_seed(42)
F=tf.constant(tf.random.uniform(shape=[50]),shape=(1,1,1,1,50))
F

<tf.Tensor: shape=(1, 1, 1, 1, 50), dtype=float32, numpy=
array([[[[[0.6645621 , 0.44100678, 0.3528825 , 0.46448255, 0.03366041,
           0.68467236, 0.74011743, 0.8724445 , 0.22632635, 0.22319686,
           0.3103881 , 0.7223358 , 0.13318717, 0.5480639 , 0.5746088 ,
           0.8996835 , 0.00946367, 0.5212307 , 0.6345445 , 0.1993283 ,
           0.72942245, 0.54583454, 0.10756552, 0.6767061 , 0.6602763 ,
           0.33695042, 0.60141766, 0.21062577, 0.8527372 , 0.44062173,
           0.9485276 , 0.23752594, 0.81179297, 0.5263394 , 0.494308  ,
           0.21612847, 0.8457197 , 0.8718841 , 0.3083862 , 0.6868038 ,
           0.23764038, 0.7817228 , 0.9671384 , 0.06870162, 0.79873943,
           0.66028714, 0.5871513 , 0.16461694, 0.7381023 , 0.32054043]]]]],
      dtype=float32)>

In [80]:
squeezed_F=tf.squeeze(F)
squeezed_F

<tf.Tensor: shape=(50,), dtype=float32, numpy=
array([0.6645621 , 0.44100678, 0.3528825 , 0.46448255, 0.03366041,
       0.68467236, 0.74011743, 0.8724445 , 0.22632635, 0.22319686,
       0.3103881 , 0.7223358 , 0.13318717, 0.5480639 , 0.5746088 ,
       0.8996835 , 0.00946367, 0.5212307 , 0.6345445 , 0.1993283 ,
       0.72942245, 0.54583454, 0.10756552, 0.6767061 , 0.6602763 ,
       0.33695042, 0.60141766, 0.21062577, 0.8527372 , 0.44062173,
       0.9485276 , 0.23752594, 0.81179297, 0.5263394 , 0.494308  ,
       0.21612847, 0.8457197 , 0.8718841 , 0.3083862 , 0.6868038 ,
       0.23764038, 0.7817228 , 0.9671384 , 0.06870162, 0.79873943,
       0.66028714, 0.5871513 , 0.16461694, 0.7381023 , 0.32054043],
      dtype=float32)>

In [85]:
tf.config.list_physical_devices()

[PhysicalDevice(name='/physical_device:CPU:0', device_type='CPU'),
 PhysicalDevice(name='/physical_device:GPU:0', device_type='GPU')]

In [86]:
!nvidia-smi

Mon Feb 20 17:30:38 2023       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 510.108.03   Driver Version: 510.108.03   CUDA Version: 11.6     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  NVIDIA GeForce ...  Off  | 00000000:01:00.0 Off |                  N/A |
| N/A   38C    P8     3W /  N/A |   3182MiB /  4096MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                               
+-------